### ISSUE TITLE
How to get the INDI(passive) interface to work?

### ISSUE THREAD

**Issue by kevinljxljx** [aaronwmorris/indi-allsky#2356]
I am running an indi-allsky instance with a pi 4 and a imx378 camera without much issue, but the 4k timelapses usually take 30-40 minutes to generate. I am trying to offload the timelapses generation to a second indi-allsky instance running on my VM. the wiki says 

"The INDI Passive interface is a special interface for allowing a second installation of indi-allsky to receive images from a camera (via an indiserver) which is being managed by another instance of indi-allsky. The Passive interface does not allow changing any settings or taking exposures, it relies on the primary indi-allsky instance to control the camera. The Passive instance just receives all of the images requested by the primary instance."

Do I just need to put the pi 4's ip address under config-camera-INDI server? I tried it but it can't connect. Or is there a different place that I can enter the pi 4's ip address?

**Comment by aaronwmorris** [comment]
Yes, you should just change the IP address of the indiserver to the PI's IP address.

You may need to update your code, I recently fixed a bug in #2319 that prevented the passive interface from operating.

**Comment by kevinljxljx** [comment]
Thanks for replying. I just installed indi-allsky yesterday, so I should have the new code I guess?
Following #2319 I found #2316, in which when I try to install indi-libcamera via 2.1.4, it errors out 

Building driver: indi-libcamera

-- The CXX compiler identification is GNU 12.2.0
-- The C compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found CFITSIO 4.2.0: /usr/lib/aarch64-linux-gnu/libcfitsio.so
-- Found INDI: /usr/local/lib/libindidriver.so;/usr/local/lib/libindiAlignmentDriver.so (found version "2.1.4")
-- Found ZLIB: /usr/lib/aarch64-linux-gnu/libz.so (found version "1.2.13")
-- Found PkgConfig: /bin/pkg-config (found version "1.8.1")
-- Found USB1: /usr/lib/aarch64-linux-gnu/libusb-1.0.so (found version "1.0.26")
-- Performing Test USB1_HAS_LIBUSB_ERROR_NAME
-- Performing Test USB1_HAS_LIBUSB_ERROR_NAME - Success
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found LIBCAMERA Library: /usr/lib/aarch64-linux-gnu/libcamera.so
CMake Error at /home/kevin/Projects/src/indi_3rdparty/cmake_modules/FindLibCameraApps.cmake:43 (message):
  LIBCAMERAAPPS Library not found.  Please install rpicam-apps
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/kevin/Projects/build/indi_3rdparty_driver.6J7LHKom/CMakeFiles/CMakeOutput.log".



but when I try to install it via HEAD, it errors out as well


Building driver: indi-libcamera

-- The CXX compiler identification is GNU 12.2.0
-- The C compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found CFITSIO 4.2.0: /usr/lib/aarch64-linux-gnu/libcfitsio.so
-- Found INDI: /usr/local/lib/libindidriver.so;/usr/local/lib/libindiAlignmentDriver.so (found version "2.1.4")
-- Found ZLIB: /usr/lib/aarch64-linux-gnu/libz.so (found version "1.2.13")
-- Found PkgConfig: /bin/pkg-config (found version "1.8.1")
-- Found USB1: /usr/lib/aarch64-linux-gnu/libusb-1.0.so (found version "1.0.26")
-- Performing Test USB1_HAS_LIBUSB_ERROR_NAME
-- Performing Test USB1_HAS_LIBUSB_ERROR_NAME - Success
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found LIBCAMERA Library: /usr/lib/aarch64-linux-gnu/libcamera.so
-- Found LIBCAMERAAPPS Library: /usr/lib/aarch64-linux-gnu/librpicam_app.so
-- Checking for module 'libraw'
--   Found libraw, version 0.20.2
-- Checking for module 'libraw_r'
--   Found libraw_r, version 0.20.2
-- Found LibRaw: /usr/lib/aarch64-linux-gnu/libraw.so (found version "0.20.2")
-- Found JPEG: /usr/lib/aarch64-linux-gnu/libjpeg.so
-- Found Boost: /lib/aarch64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: program_options
-- Performing Test COMPATIBLE_FORTIFY_SOURCE
-- Performing Test COMPATIBLE_FORTIFY_SOURCE - Success
-- Performing Test COMPATIBLE_STRINGOP_TRUNCATION
-- Performing Test COMPATIBLE_STRINGOP_TRUNCATION - Success
-- Performing Test COMPATIBLE_UNUSED_PARAMETER
-- Performing Test COMPATIBLE_UNUSED_PARAMETER - Success
-- Performing Test COMPATIBLE_UNUSED_BUT_SET_VARIABLE
-- Performing Test COMPATIBLE_UNUSED_BUT_SET_VARIABLE - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kevin/Projects/build/indi_3rdparty_driver.PjJMTv6q
[ 25%] Building CXX object CMakeFiles/rpicam_test.dir/rpicam_test.cpp.o
[ 50%] Building CXX object CMakeFiles/indi_libcamera_ccd.dir/indi_libcamera.cpp.o
In file included from /home/kevin/Projects/src/indi_3rdparty/indi-libcamera/indi_libcamera.h:27,
                 from /home/kevin/Projects/src/indi_3rdparty/indi-libcamera/indi_libcamera.cpp:21:
/usr/include/rpicam-apps/core/rpicam_encoder.hpp: In member function ‘void RPiCamEncoder::encodeBufferDone(void*)’:
/usr/include/rpicam-apps/core/rpicam_encoder.hpp:94:37: error: unused parameter ‘mem’ [-Werror=unused-parameter]
   94 |         void encodeBufferDone(void *mem)
      |                               ~~~~~~^~~
[ 75%] Linking CXX executable rpicam_test
[ 75%] Built target rpicam_test
cc1plus: some warnings being treated as errors
make[2]: *** [CMakeFiles/indi_libcamera_ccd.dir/build.make:76: CMakeFiles/indi_libcamera_ccd.dir/indi_libcamera.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/indi_libcamera_ccd.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

can't seem to get it to install.

**Comment by aaronwmorris** [comment]
There is a known issue related to compiling indi-libcamera right now.  The rpicam developers keep changing their interface.

https://github.com/indilib/indi-3rdparty/issues/1128

Let me do some testing...

**Comment by kevinljxljx** [comment]
Yes I saw indi v2.1.5 indi_libcamera_ccd will not build in the readme so I installed v2.1.4 thinking it should work, but nope it didn't. I guess it is not the indi version issue.... 

A side question: if this works, I should be able just install indi server on the pi and use indi web on the vm to control the camera right? I tried it yesterday but only the indi web can't see the camera on the pi either. I guess it is the same problem as what I am trying to do now?

**Comment by aaronwmorris** [comment]
Yeah, I was not very specific in the description.  The problem is not really indi, but the libcamera source.  It just became a problem when indi v2.1.5 was released.  It technically affects all versions of INDI.  The fix is in the HEAD branch, its just not part of a tagged release yet (of indi-3rdparty)

If you get this built, indi-allsky would be able to control the camera via a remote indiserver connection, yes.

**Comment by kevinljxljx** [comment]
> If you get this built, indi-allsky would be able to control the camera via a remote indiserver connection, yes.

This seems like a better way to do it (at least for me). It gets really hot here where I live even it is Sep already. The camera and pi's cpu temp can reach 75C just taking photos during the day, so it really lags when it is starts to create a timelapse, not to mention pi4's processor is not that fast anyway. If this works, I am guessing it will take a chunk of load off the pi and make it just a bit cooler.

**Comment by kevinljxljx** [comment]
After some digging, I can successfully build the indi-libcamera now. I just have to build it from the indi-3rdparty repo and it worked as far as the connecting two indi-allsky instances. However, for some reasons, the driver sees my imx378 as imx477, weird. The contrast, and the saturation goes all over the place as well. Also, the driver can't read sensor temp either. I am guessing I just have to wait for that driver to get more mature and try it later. During the meantime, is there another way to send photos to a second indi-allsky and create the timelapse there? Like using the syncapi? the doc says it will sync photo and timelapse, but if I just sync the photo to the second indi-allsky, does it create timelapses? 

Thanks for the help!

**Comment by aaronwmorris** [comment]
I have fixed my scripts building of indi-libcamera on the HEAD branch with #2358 .

The IMX378 is extremely similar to the IMX477, so that is not too surprising.  Is it possible you left the camera auto-detection enabled and it just misdetected it?  You may need to disable in `/boot/firmware/config.txt` and manually enable the imx378 overlay instead.  I may be mis-remembering, but I thought the temperature was reported with the imx378.

For the time being, this is the only way.  The syncapi does not really have the ability to function this way.  You could also try https://github.com/aaronwmorris/indi-allsky/wiki/indi_pylibcamera-setup

**Comment by kevinljxljx** [comment]
> You may need to disable in /boot/firmware/config.txt and manually enable the imx378 overlay instead

Yes I did edit the config.txt for imx378, but the indi-libcamera driver still sees it as imx477, and doesn't report sensor temp. I don't really care about these two though. The main issue is the photo doesn't come out right with indi-libcamera driver. It seems to have more noise even during the day (gain is set to 1), and the contrast and saturation is way off. I tried to adjust it with every setting possible, but it just doesn't turn out as good as the regular libcamera driver. Also the exposure seems to be unstable. Like the first 10 photos will be super dark, but the next 10 will be super bright, and the next 10 will be dark again... weird.... 

I am thinking just leave it and let it run with regular libcamera driver, and see if it can be stable in the long run. I just need to remember not to touch it when it is generating timelapse to avoid any lag. In the future, I might upgrade the camera to a zwo ASI676MC. It seems to produce a better picture quality anyway. 

Thanks for the help again :)

**Comment by aaronwmorris** [comment]
I have some theories on how I can create an MQTT controlled camera where it uses the rpicam-still command like the libcamera drivers so it would not require an indiserver on the remote system.  If you are interested, I can re-open this and I will eventually get around to developing this function.

**Comment by kevinljxljx** [comment]
I feel like it would make things more complicated. When I research allsky camera build, half if not most people use some sort of astro camera, which doesn't require libcamera, and for those who does use a pi camera, libcamera works fairly well. Of course it is nice to have the pi just taking pictures and use the vm to do the heavy lifting. I feel more toward to wait for indi-libcamera to finish developing and see how it goes from there. And of course there is indi_pylibcamera, but I didn't try it since it is more resource hungry.

**Comment by aaronwmorris** [comment]
I have the feeling that the indi-libcamera driver is always going to be a second-class feature for INDI.  I fully expect it to be 2+ years before we can expect more serious development.  (Not that the INDI team has not already performed a miracle making it work.)

Libcamera has not even reached version 1.0 and the API/ABI is not stable.  At the rate the versions are increasing, version 1.0 is probably 1-2 years away.  Until things stabilize, it is probably not worth investing the effort.

**Comment by kevinljxljx** [comment]
yeah 2+ years of wait will be way too long to hope for, which makes your MQTT controlled camera sounds more interesting. 

Correct me if I am wrong. indi-allsky actually doesn't use indi server if I choose to use imx378 with libcamera driver, and that's why when I try to use indi passive, it can't see the camera. It only sees the camera if I choose to use indi as camera interface and use indi-libcamera driver (camera though indi server). Therefore, if we decided to go with the MQTT route, then the pi only needs mqtt client and camera driver (for controlling camera and sending photos), and the vm needs another mqtt client and a broker (web only install maybe?).  Not sure if we can still have full camera control if we go with this route. I was thinking to use a ip cam with my build, but I can't control the camera exposure with ip cam, so I went with the imx378. It will be great if we can still have the full control of the camera while have the pi and vm separate, then please re-open this and make it a feature request :)

Also a side note: if this works, maybe we can have multiple pi cameras connect to a central server with the main indi-allsky instance, and we can choose which camera/timelapses to view by switching with the top left side of the website where you can choose different cameras now. This will make it more useful as a timelapses platform. Like one or two cameras for allsky, another one for pet etc.

**Comment by aaronwmorris** [comment]
Hopefully 3 days was not too long to wait.  I have merged #2369 which is a new interface to control a remote libcamera based CSI/MIPI camera via MQTT.

Exposure requests are sent via MQTT and are picked up by a script running on the remote Raspberry Pi.  The script runs rpicam-still and return the image and metadata back using a different topic.

Script:  `./misc/mqtt_remote_libcamera.py`

On the topic of multiple cameras... that is a different challenge.  The database and web interface can handle multiple cameras simultaneously, but the capture process really only supports one currently.  You could have two instances of indi-allsky, and one of them using the SyncAPI to send images to the other, that way all of the data is combined, but capturing two cameras simultaneously is not currently a capability.

**Comment by kevinljxljx** [comment]
You are awesome! It will take a day or two before I can get to test this though. I just turned off AWB and see how it goes. #2364 I figure it will be best to keep changes to minimum to make the test consistent.

**Comment by kevinljxljx** [comment]
I just updated the indi allsky in vm and it looks ok. but when I get to the pi, do I just need to run the mqtt_remote_libcamera.py and that's it? Without any installation? (indi server, web install etc.)

**Comment by kevinljxljx** [comment]
Never mind. I found that in indiserver install script. :)

**Comment by aaronwmorris** [comment]
You really just need `rpicam-apps` and `python3-paho-mqtt`

**Comment by kevinljxljx** [comment]
Forgive me if I miss something. I updated the repo on both pi and vm. reinstalled indi-allsky on vm and is able to see mqtt interface and entered pi's ip address. Stopped all indi-allsky services per wiki. Ran the indiserver_only_setup script and chose mqtt imx378 camera interface. However, the indi-allsky on vm can't connect to the pi (got ConnectionRefusedError: [Errno 111] Connection refused in log). I tried to connect the pi via mqtt with MQTTX and got the same connection refused error. Ran the mqtt_remote_libcamera.py script itself on the pi, and got connection refused error too. Maybe the script doesn't install the mqtt broker and I need to install it myself? But when I ran the script to connect my own mqtt broker for IOT stuffs, it gave me a timeout error. What am I missing?

**Comment by aaronwmorris** [comment]
The indiserver script does not setup the broker.  I will need to consider that flow in the setup script.

You can run `./misc/setup_mosquitto_mqtt.sh` to setup mosquitto on your VM.

**Comment by kevinljxljx** [comment]
Yeah that's what I figured. I just got it working. Now the vm can remotely taking picture with the pi camera, but the image looks washed out just like when I use the indi-libcamera. I tried to adjust the saturation, gamma, contrast enhance, MTF cutoff, stretch function but still can't get it to look right (like the image from standalone pi indi-allsky). Any ideas why? 
![Image](https://github.com/user-attachments/assets/85172749-aa72-42b4-80d3-e2101a69bcd0)

**Comment by aaronwmorris** [comment]
I noticed the same issue and it did not click for me then.  I have some libcamera specific code paths that I need to add to these new driver profiles.

In the mean time, the issue is that libcamera sets a massive offset (in astronomy camera terms) of 4096 which gives the images a washed out look.  libcamera calls this the "black level". The code path I mentioned automatically subtracts the offset if dark frames are not found.  The value of 4096 is in a 16-bit space, which translates to 16,16,16 RGB in a 8-bit image.  It is quite high.  (Also... dark frames would fix this, too.)

There is a manual override in indi-allsky.  On the Image tab, at the top near the dark frame setting, you can enter a manual offset to be subtracted from the images.  I would try 4096 and see how that looks.

Edit:  Merged #2375 to update code paths.

**Comment by kevinljxljx** [comment]
The image looks right after changing the offset to 4096. Thanks a lot! I just need to use screen to keep the py script running in the background that everything seems to be working perfectly. I am guessing the original indi-libcamera exposure issue has something to do with the AWB and offset as well. I tried to do a test with the indi-libcamera driver, but somehow even if i followed the original steps ( install the indi-libcamera driver, do a indi-server-only install, choose indi interface, indi-libcamera driver), the vm keeps saying no camera. weird....

**Comment by kevinljxljx** [comment]
I just did a rebuild of indi-libcamera driver and now everything works (except instead of showing the true ccd temp, it just shows -273.1C. Maybe it is a state of the art astro cooled camera lol. Also on the vm side, the overlay can't see the pi's cpu temp). The exposure and contrast issue I mentioned above was solved as well by turning off AWB and setting the 4096 offset.
